// clearly autogenerated code lol
export function debounceAsyncFn<T extends unknown[], R>(
    fn: (...args: T) => Promise<R>,
    delay: number,
): (...args: T) => Promise<R> {
    let timeoutId: NodeJS.Timeout | null = null;

    return (...args: T): Promise<R> => {
        return new Promise((resolve, reject) => {
            if (timeoutId) {
                clearTimeout(timeoutId);
            }

            timeoutId = setTimeout(() => {
                fn(...args)
                    .then(resolve)
                    .catch(reject);
            }, delay);
        });
    };
}